### PR TITLE
Implemented Transporter screen

### PR DESCRIPTION
**Pull request by Albinseban2021**

### CODE REVIEW

**Comment by Anik-Chakraborty** [comment]
image
fix the design..... the 3 dots in vendor code should be aligned at the end...
Remove spaces around the title (transporter) and search bar and add transporter button .... also table should be lifted.

**Comment by Anik-Chakraborty** [comment]
image
Name of the transporter is by default Liveasy....

**Comment by Anik-Chakraborty** [comment]
Maintain a symmetric design ... current design is not consistence and doesn't goes with actual figma design

**Comment by Anik-Chakraborty** [comment]
image
Liveasy Logo is not visible

**Comment by Albinseban2021** [comment]
> image Name of the transporter is by default Liveasy....

In Figma design, by default, the transporter name should be set to Livesay

**Pull request merged**
